Fixing push issue, add Dockerfile.vmware.cpu for tensorflow training
liuqi/deep-learning-containers pull request #1
Opened 2022-05-18 02:37 UTC by AmyHoney

*GitHub Issue #, if available:*

Note: If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

### Description

### Tests run
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating the dlc_developer_config.toml file:**

- [ ] Revision A: `sagemaker_remote_tests = "standard"`
- [ ] Revision B: `sagemaker_remote_tests = "rc"`
- [ ] Revision C: `sagemaker_remote_tests = "efa"`

**Additionally, please run the sagemaker local tests in at least one revision:**
- [ ] `sagemaker_local_tests = true`

### DLC image/dockerfile

### Additional context

## Label Checklist
- [ ] I have added the project label for this PR (*<project_name>* or "Improvement")

## PR Checklist
- [ ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron/graviton] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [ ] If the PR changes affects SM test, I've modified dlc_developer_config.toml in my PR branch by setting sagemaker_tests = true and efa_tests = true
- [ ] If this PR changes existing code, the change fully backward compatible with pre-existing code. (Non backward-compatible changes need special approval.)
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

## Pytest Marker Checklist
- [ ] (If applicable) I have added the marker `@pytest.mark.model("<model-type>")` to the new tests which I have added, to specify the Deep Learning model that is used in the test (use `"N/A"` if the test doesn't use a model)
- [ ] (If applicable) I have added the marker `@pytest.mark.integration("<feature-being-tested>")` to the new tests which I have added, to specify the feature that will be tested
- [ ] (If applicable) I have added the marker `@pytest.mark.multinode(<integer-num-nodes>)` to the new tests which I have added, to specify the number of nodes used on a multi-node test
- [ ] (If applicable) I have added the marker `@pytest.mark.processor(<"cpu"/"gpu"/"eia"/"neuron">)` to the new tests which I have added, if a test is specifically applicable to only one processor type

#### EIA/NEURON/GRAVITON Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `ei_mode = true`, `neuron_mode = true` or `graviton_mode = true`

#### Benchmark Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `benchmark_mode = true`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-07 15:11 UTC, liuqi requested changes
The comments for the changes under src/ and tensorflow/

2022-06-07 15:11 UTC, liuqi commented on src/image.py
> +        # print(registry_name)
Remove the debug output

2022-06-07 15:11 UTC, liuqi commented on src/image.py
> +        # registry_name = "harbor-repo.vmware.com"
Remove?

2022-06-07 15:11 UTC, liuqi commented on src/image.py
> +        # registry_name = "harbor-repo.vmware.com"
Remove?

2022-06-07 15:11 UTC, liuqi commented on src/image_builder.py
> +            # "region": str(BUILDSPEC["region"]),
Remove?

2022-06-07 15:11 UTC, liuqi commented on src/image_builder.py
> +            # "region": str(BUILDSPEC["region"]),
Remove?

2022-06-07 15:11 UTC, liuqi commented on src/registry.py
> +                return
If this is copied from somewhere, be careful about the license, copyright, et al.

2022-06-07 15:11 UTC, liuqi commented on src/registry.py
> +                return
If this is copied from somewhere, be careful about the license, copyright, et al.

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
>      boto3 \
Remove?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
>      boto3 \
Remove?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> + && rm -rf /var/lib/apt/lists/*
Reliable method to install tensorflow_model_server?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> + && rm -rf /var/lib/apt/lists/*
Reliable method to install tensorflow_model_server?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> + && echo '/usr/bin/tensorflow_model_server --port= --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"' >> /usr/bin/tf_serving_entrypoint.sh \
why 8500 is removed?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> + && echo '/usr/bin/tensorflow_model_server --port= --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"' >> /usr/bin/tf_serving_entrypoint.sh \
why 8500 is removed?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> -RUN chmod +x /usr/local/bin/deep_learning_container.py
what does deep_learning_container.py do?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> -RUN chmod +x /usr/local/bin/deep_learning_container.py
what does deep_learning_container.py do?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> -RUN curl https://aws-dlc-licenses.s3.amazonaws.com/tensorflow-2.8/license.txt -o /license.txt
we should be careful about the license related files.

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> -RUN curl https://aws-dlc-licenses.s3.amazonaws.com/tensorflow-2.8/license.txt -o /license.txt
we should be careful about the license related files.

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
>      boto3 \
remove?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
>      boto3 \
remove?

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
> -RUN chmod +x /usr/local/bin/deep_learning_container.py
ditto

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
> -RUN chmod +x /usr/local/bin/deep_learning_container.py
ditto

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
> -
ditto

2022-06-07 15:11 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/cu112/Dockerfile.gpu
> -
ditto

2022-06-07 15:11 UTC, liuqi commented on tensorflow/training/docker/2.8/py3/Dockerfile.cpu
ditto

2022-06-07 15:11 UTC, liuqi commented on tensorflow/training/docker/2.8/py3/Dockerfile.cpu
ditto

2022-06-07 15:11 UTC, liuqi commented on tensorflow/training/docker/2.8/py3/cu112/Dockerfile.gpu
> -
ditto

2022-06-07 15:11 UTC, liuqi commented on tensorflow/training/docker/2.8/py3/cu112/Dockerfile.gpu
> -
ditto

2022-06-08 04:01 UTC, liuqi requested changes
part 2 - for the changes under mxnet/ and pytorch/

2022-06-08 04:01 UTC, liuqi commented on mxnet/buildspec.yml
> +#       target: deep_learning_container.py
Same questions on entrypoint...

2022-06-08 04:01 UTC, liuqi commented on mxnet/inference/docker/1.9/py3/Dockerfile.cpu
>      boto3 \
remove?

2022-06-08 04:01 UTC, liuqi commented on mxnet/inference/docker/1.9/py3/cu112/Dockerfile.gpu
> +ARG MX_URL=https://opentuna.cn/pypi/web/packages/e4/07/d9a40f4a6347d80cea2ef32c3a2f2a40f150592ca132d2986ce835ecfe7d/mxnet_cu112-1.9.0-py3-none-manylinux2014_x86_64.whl
looks like not an reliable source

2022-06-08 04:01 UTC, liuqi commented on mxnet/training/docker/1.9/py3/cu112/Dockerfile.gpu
> +    NVIDIA_REQUIRE_CUDA="cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450"
the requirement is related to specific hardware version?

2022-06-08 04:01 UTC, liuqi commented on pytorch/buildspec.yml
> +    image_size_baseline: 4000
just to ask, why we need this change?

2022-06-08 04:01 UTC, liuqi commented on pytorch/inference/docker/1.11/py3/Dockerfile.cpu
> + && rm ~/miniconda.sh \
why replace mambaforge with miniconda?

2022-06-08 04:01 UTC, liuqi commented on pytorch/inference/docker/1.11/py3/Dockerfile.cpu
>      boto3 \
remove?

2022-06-08 04:01 UTC, liuqi commented on pytorch/inference/docker/1.11/py3/cu113/Dockerfile.gpu
> + && /opt/conda/bin/conda install -y \
ditto

2022-06-08 04:01 UTC, liuqi commented on pytorch/training/docker/1.11/py3/Dockerfile.cpu
> +    ruamel_yaml==0.15.100 \
ditto

2022-06-08 04:01 UTC, liuqi commented on pytorch/training/docker/1.11/py3/cu113/Dockerfile.gpu
> + && rm ~/miniconda.sh \
ditto

2022-06-08 07:32 UTC, AmyHoney commented on src/image.py
> +        # print(registry_name)
Done

2022-06-08 07:32 UTC, AmyHoney commented on src/image.py
> +        # registry_name = "harbor-repo.vmware.com"
Done

2022-06-08 07:32 UTC, AmyHoney commented on src/image.py
> +        # registry_name = "harbor-repo.vmware.com"
Done

2022-06-08 07:32 UTC, AmyHoney commented on src/image_builder.py
> +            # "region": str(BUILDSPEC["region"]),
Done

2022-06-08 07:33 UTC, AmyHoney commented on src/image_builder.py
> +            # "region": str(BUILDSPEC["region"]),
Done

2022-06-08 12:43 UTC, liuqi requested changes
two minor issues

2022-06-08 12:43 UTC, liuqi commented on tensorflow/inference/docker/2.8/py3/Dockerfile.cpu
> + && echo '/usr/bin/tensorflow_model_server --port= --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"' >> /usr/bin/tf_serving_entrypoi
--port= --port=8500  ----->  --port=8500

2022-06-08 12:43 UTC, liuqi commented on .github/ISSUE_TEMPLATE/custom.md
> +
Please remove this change.

2022-06-08 13:53 UTC, AmyHoney commented
> two minor issues

Fixing these two minor issues! Please review!

2022-06-10 06:59 UTC, merged